language: objective-c
os: osx
osx_image: xcode11
before_install:
  - gem install xcpretty
  - carthage update --no-use-binaries --platform ios
before_script:
  - set -o pipefail
script:
  - xcodebuild test -project ./Unio.xcodeproj -scheme Unio -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone 8' | xcpretty -c
notifications:
  email: false
